coverage:
  status:
    # 若 PR 使总覆盖率下降超过 2% 则判定失败
    project:
      default:
        target: auto
        threshold: 2%
    # 将 patch 覆盖率仅视为参考信息
    patch:
      default:
        informational: true
comment:
  hide_project_coverage: false
